apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: usuario-ms
  name: usuario-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuario-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: usuario-ms
    spec:
      nodeName: aks-agentpool-37946828-vmss000001
      serviceAccountName: default       # <--- esto asegura que use tu ServiceAccount
      imagePullSecrets:
        - name: azure-key3
      containers:
      - image: tiendaimagesunl.azurecr.io/usuario-ms
        name: usuario-ms
        env:
        - name: PORT
          value: "3004"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: usuario-secrets
              key: database_url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: usuario-secrets
              key: jwt_secret
        resources:
          requests:
            memory: "300Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "80m"
status: {}
