version: '3'

volumes:
  grafana-data:
  prometheus-data:
services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  client-gateway:
    build: ./client-gateway
    ports:
      - 3000:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

#======================================================
# STORES LOCAL
#=======================================================
  store-ms:
    build: ./stores-microservice
    volumes:
      - ./stores-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3011
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${DATABASE_URL_STORES}
    depends_on:
      stores-db:
        condition: service_healthy 

  stores-db:
    container_name: stores_ms_db
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres/stores:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=stores-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 15s
      retries: 10
#======================================================
# PRODUCTS LOCAL
#=======================================================
  productss-ms:
    build: ./productss-microservice
    volumes:
      - ./productss-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3010
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${DATABASE_URL_PRODUCTSS}
    depends_on:
      products-db:
        condition: service_healthy 

  products-db:
    container_name: products_db
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres/products:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=products-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 15s
      retries: 10
#======================================================
# ORDENES LOCAL
#=======================================================
  orders-ms:
    build: ./orders-microservice
    volumes:
      - ./orders-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - DATABASE_URL=${DATABASE_URL_POSTGRES}
      - NATS_SERVERS=nats://nats-server:4222
    depends_on:
      orders-db:
        condition: service_healthy  

#======================================================
# USUARIOS LOCAL
#=======================================================
  auth-ms:
    build: ./auth-microservice
    volumes:
      - ./auth-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
