# version: '3'

services:

#=====================================
# NATS
#====================================
  nats-server:
    image: nats:latest


#=====================================
# BACKEND
#=====================================

  auth-ms:
    build: 
      context: ./usuario-ms
      dockerfile: dockerfile.prod
    image: jhairagila/auth-ms
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  api-gateway: 
    build: 
      context: ./api-gateway
      dockerfile: dockerfile.prod
    image: jhairagila/client-gateway 
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  producto-ms:
    build: 
      context: ./producto-ms
      dockerfile: dockerfile.prod
      args:
        - PRODUCTS_DB_URL_NEON=${PRODUCTS_DB_URL_NEON}
    # image: us-west1-docker.pkg.dev/tienda-ms-452101/image-registry/products-ms
    image: jhairagila/products-ms
    environment:
      - PORT=3002
      - DATABASE_URL=${PRODUCTS_DB_URL_NEON}
      - NATS_SERVERS=nats://nats-server:4222

  stores-ms:
    build: 
      context: ./stores-microservice
      dockerfile: dockerfile.prod
      args:
        - STORES_DB_URL_NEON=${STORES_DB_URL_NEON}
    image: jhairagila/stores-ms
    environment:
      - PORT=3002
      - DATABASE_URL=${STORES_DB_URL_NEON}
      - NATS_SERVERS=nats://nats-server:4222
  
  
  

  
