version: '3'
services:

#======================================================
# NATS SERVER
#=======================================================
  nats:
    image: nats:latest
    ports:
      - "4222:4222"

#======================================================
# API GATEWAY
#=======================================================
  api-gateway:
    build: ./api-gateway
    ports:
      - 3000:3000
    volumes:
      - ./api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      
#======================================================
# PRODUCTO MICROSERVICE
#=======================================================
  producto-ms:
    build: ./producto-ms
    ports:
      - 3001:3001
    volumes:
      - ./producto-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222

#======================================================
# TIENDA MICROSERVICE
#=======================================================
  tienda-ms:
    build: ./tienda-ms
    ports:
      - 3002:3002
    volumes:
      - ./tienda-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
  
#======================================================
# USUARIO MICROSERVICE
#=======================================================
  usuario-ms:
    build: ./usuario-ms
    volumes:
      - ./usuario-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

