apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tienda-cert
  namespace: default
spec:
  secretName: tienda-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - azure.tesisunlloja.site
