apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-backend-config
spec:
  timeoutSec: 200           # Aumenta de 30s a 60s
  connectionDraining:
    drainingTimeoutSec: 30
  healthCheck:
    requestPath: /   # Usa un endpoint r√°pido
    port: 3000