apiVersion: apps/v1
kind: Deployment
metadata:
  name: producto-ms
  labels:
    app: producto-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producto-ms
  template:
    metadata:
      labels:
        app: producto-ms
    spec:
      nodeName: aks-agentpool-37946828-vmss000001
      # Permite que el usuario 'node' (UID 1000) tenga acceso de escritura al volumen
      securityContext:
        fsGroup: 1000
      containers:
        - name: producto-ms
          image: tiendaimagesunl.azurecr.io/producto-ms
          ports:
            - containerPort: 3010
          env:
            - name: PORT
              value: "3010"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: producto-secrets
                  key: database_url
            - name: NATS_SERVERS
              value: "nats://nats"
          # Montamos el volumen persistente dentro del contenedor
          resources:
            requests:
              memory: "300Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "80m"
          volumeMounts:
            - name: producto-storage
              mountPath: /usr/src/app/uploads
      # Declaramos el volumen que usar√° el contenedor
      volumes:
        - name: producto-storage
          persistentVolumeClaim:
            claimName: producto-pvc-premium
