apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: premium-ssd-v2-customm
provisioner: disk.csi.azure.com
parameters:
  skuName: PremiumV2_LRS     # Tipo de disco
  diskIOPSReadWrite: "4000"  # IOPS deseados
  diskMBpsReadWrite: "250"   # Throughput (MB/s)
allowVolumeExpansion: true
volumeBindingMode: Immediate