apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tienda-ms
  name: tienda-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tienda-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tienda-ms
    spec:
      nodeName: aks-agentpool-37946828-vmss000001
      containers:
      - image: tiendaimagesunl.azurecr.io/tienda-ms
        name: tienda-ms
        env:
        - name: PORT 
          value: "3010"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tienda-secrets
              key: database_url
        - name: NATS_SERVERS
          value: "nats://nats"
        resources:
          requests:
            memory: "300Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "80m"
status: {}
