apiVersion: apps/v1
kind: Deployment
metadata:
  name: producto-ms
  labels:
    app: producto-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producto-ms
  template:
    metadata:
      labels:
        app: producto-ms
    spec:
      securityContext:
        fsGroup: 1000 
      nodeName: gke-cluster-1-default-pool-424600d3-s79d
      containers:
        - name: producto-ms
          image: us-central1-docker.pkg.dev/tt-eccomerce-tesis/tiendaimagenes/producto-ms
          env:
            - name: PORT
              value: "3010"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: producto-secrets
                  key: database_url
            - name: NATS_SERVERS
              value: "nats://nats"
          resources:
            requests:
              memory: "300Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "80m"
          volumeMounts:
            - name: producto-storage
              mountPath: /usr/src/app/uploads
      volumes:
        - name: producto-storage
          persistentVolumeClaim:
            claimName: hyperdisk-pvc-custom
